// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2RT1twTWsmntN7hIqcYCNNCjD6DrZGjg',
    appId: '1:444290227098:web:c47bf6402a0bde4449f823',
    messagingSenderId: '444290227098',
    projectId: 'helenium-798a8',
    authDomain: 'helenium-798a8.firebaseapp.com',
    storageBucket: 'helenium-798a8.firebasestorage.app',
    measurementId: 'G-3RT1CH9NPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6SeqUn7fUAO7D3-XY5DU6D0ZKmjwSIw',
    appId: '1:444290227098:android:b4294f4e4a4f53d649f823',
    messagingSenderId: '444290227098',
    projectId: 'helenium-798a8',
    storageBucket: 'helenium-798a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbDNVkweSrx4PNBcSDElDfHSfRUfuoR4',
    appId: '1:444290227098:ios:58bfbbd1b7243dec49f823',
    messagingSenderId: '444290227098',
    projectId: 'helenium-798a8',
    storageBucket: 'helenium-798a8.firebasestorage.app',
    iosClientId: '444290227098-vh0higrtr2q6qvsorsanupdqbl7vcdh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlbDNVkweSrx4PNBcSDElDfHSfRUfuoR4',
    appId: '1:444290227098:ios:58bfbbd1b7243dec49f823',
    messagingSenderId: '444290227098',
    projectId: 'helenium-798a8',
    storageBucket: 'helenium-798a8.firebasestorage.app',
    iosClientId: '444290227098-vh0higrtr2q6qvsorsanupdqbl7vcdh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2RT1twTWsmntN7hIqcYCNNCjD6DrZGjg',
    appId: '1:444290227098:web:70e3245f15de8a1d49f823',
    messagingSenderId: '444290227098',
    projectId: 'helenium-798a8',
    authDomain: 'helenium-798a8.firebaseapp.com',
    storageBucket: 'helenium-798a8.firebasestorage.app',
    measurementId: 'G-NY0FNE1WRY',
  );

}